# TODO: Translation updated at 2022-01-11 21:45

translate vietnamese strings:

    # game/options.rpy:19
    old "Learn to Code RPG"
    new "Học Lập Trình RPG"

    # game/options.rpy:36
    old "{b}Learn to Code RPG{/b} is a game where you teach yourself to code, make friends in the tech industry, and pursue your dream to become a developer."
    new "{b}Học Lập Trình RPG{/b} là một trò chơi nơi bạn tự học lập trình, kết bạn trong ngành công nghệ, và theo đuổi ước mơ trở thành lập trình viên."

    # game/options.rpy:40
    old "This game was made possible by all the kind people who donate to support freeCodeCamp.org. You can help support our nonprofit's mission {a=https://www.freecodecamp.org/news/how-to-donate-to-free-code-camp/}here{/a}.\n\nThis project is open source and is currently in beta. If you notice any bugs or have suggestions about accessibility, the interface, the story, or anything at all, please report them on our {a=https://github.com/freeCodeCamp/LearnToCodeRPG}GitHub repo{/a}.\n\nIf you are enjoying this game, please {icon=icon-thumbs-up} rate and review us on {a=https://freecodecamp.itch.io/learn-to-code-rpg}itch.io{/a}."
    new "Trò chơi này được tạo ra nhờ sự ủng hộ của những người tốt bụng đã quyên góp cho freeCodeCamp.org. Bạn có thể giúp ủng hộ sứ mệnh phi lợi nhuận của chúng tôi {a=https://www.freecodecamp.org/news/how-to-donate-to-free-code-camp/}tại đây{/a}.\n\nDự án này là mã nguồn mở và hiện đang trong giai đoạn thử nghiệm. Nếu bạn phát hiện lỗi hoặc có góp ý về khả năng tiếp cận, giao diện, cốt truyện hay bất cứ điều gì, vui lòng báo cáo trên {a=https://github.com/freeCodeCamp/LearnToCodeRPG}GitHub repo{/a} của chúng tôi.\n\nNếu bạn đang thích trò chơi này, hãy {icon=icon-thumbs-up} đánh giá và nhận xét chúng tôi trên {a=https://freecodecamp.itch.io/learn-to-code-rpg}itch.io{/a}."

    # game/options.rpy:48
    old "Creative Lead: {a=https://ruolinzheng08.github.io/}Lynn Zheng (Ruolin Zheng){/a} {a=https://github.com/RuolinZheng08/}{icon=icon-github}{/a} {a=https://www.youtube.com/channel/UCZ2MeG5jTIqgzEMiByrIzsw}{icon=icon-youtube}{/a} {a=https://www.linkedin.com/in/ruolin-zheng/}{icon=icon-linkedin}{/a} {a=https://twitter.com/lynnzheng08}{icon=icon-twitter}{/a}\n\nCoding & Writing & Misc. Art: {a=https://ruolinzheng08.github.io/}Lynn Zheng (Ruolin Zheng){/a}\n\nMusic: {a=https://twitter.com/ossia}Quincy Larson{/a}\n\nCharacter Art: {a=https://layerto.carrd.co}Layerto (Noa Trinh){/a}\n\nQuiz Questions & Proofreading: {a=https://twitter.com/abbeyrenn}Abbey Rennemeyer{/a}, {a=https://github.com/ojeytonwilliams/}Oliver Eyton-Williams{/a}, {a=https://twitter.com/EstefaniaCassN}Estefania Cassingena Navone{/a}, {a=https://twitter.com/codergirl1991}Jessica Wilkins{/a}, {a=https://twitter.com/deniselemonaki}Dionysia Lemonaki{/a}\n\nPlaytesting: {a=https://twitter.com/ieahleen}Ilenia Magoni{/a}, {a=https://twitter.com/EstefaniaCassN}Estefania Cassingena Navone{/a}, {a=https://twitter.com/nhcarrigan}Naomi Carrigan{/a}, {a=https://twitter.com/_sidemt}Yoko Matsuda{/a}, {a=https://twitter.com/Daniel__Rosa}Daniel Rosa{/a}, {a=https://twitter.com/beaucarnes}Beau Carnes{/a}\n\nAnd thank you for playing the game :)"
    new "Chủ Biên Sáng Tạo: {a=https://ruolinzheng08.github.io/}Lynn Zheng (Ruolin Zheng){/a} {a=https://github.com/RuolinZheng08/}{icon=icon-github}{/a} {a=https://www.youtube.com/channel/UCZ2MeG5jTIqgzEMiByrIzsw}{icon=icon-youtube}{/a} {a=https://www.linkedin.com/in/ruolin-zheng/}{icon=icon-linkedin}{/a} {a=https://twitter.com/lynnzheng08}{icon=icon-twitter}{/a}\n\nLập Trình & Viết Kịch Bản & Nghệ Thuật Tổng Hợp: {a=https://ruolinzheng08.github.io/}Lynn Zheng (Ruolin Zheng){/a}\n\nÂm Nhạc: {a=https://twitter.com/ossia}Quincy Larson{/a}\n\nNghệ Thuật Nhân Vật: {a=https://layerto.carrd.co}Layerto (Noa Trinh){/a}\n\nCâu Hỏi Trắc Nghiệm & Hiệu Đính: {a=https://twitter.com/abbeyrenn}Abbey Rennemeyer{/a}, {a=https://github.com/ojeytonwilliams/}Oliver Eyton-Williams{/a}, {a=https://twitter.com/EstefaniaCassN}Estefania Cassingena Navone{/a}, {a=https://twitter.com/codergirl1991}Jessica Wilkins{/a}, {a=https://twitter.com/deniselemonaki}Dionysia Lemonaki{/a}\n\nThử Nghiệm Trò Chơi: {a=https://twitter.com/ieahleen}Ilenia Magoni{/a}, {a=https://twitter.com/EstefaniaCassN}Estefania Cassingena Navone{/a}, {a=https://twitter.com/nhcarrigan}Naomi Carrigan{/a}, {a=https://twitter.com/_sidemt}Yoko Matsuda{/a}, {a=https://twitter.com/Daniel__Rosa}Daniel Rosa{/a}, {a=https://twitter.com/beaucarnes}Beau Carnes{/a}\n\nVà cảm ơn bạn đã chơi trò chơi :)"
